{{- if .Values.networkpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        # Nginx ingress (RKE2)
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        # Istio ingressgateway
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 3000

  egress:
    # hacia backend
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.podPort }}

    # DNS (CRÍTICO)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
{{- end }}
