{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ default (include "webapp.fullname" .) .Values.sealedSecret.name }}
  annotations:
    {{- toYaml .Values.sealedSecret.annotations | nindent 4 }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecret.encryptedData | nindent 4 }}
{{- end }}
