apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-frontend
  namespace: argocd
spec:
  project: default

  sources:

    # 🔹 Source 1 → Namespace
    - repoURL: https://github.com/kdvops/openclaw.git
      targetRevision: main
      path: k8s/apps/openclaw/frontend/namespace/


    # 🔹 Source 2 → Helm App
    - repoURL: https://github.com/kdvops/openclaw.git
      targetRevision: main
      path: k8s/apps/openclaw/frontend/webapp
      helm:
        valueFiles:
          - values.yaml
        parameters:
          - name: fullnameOverride
            value: frontend


  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true