apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-comercial-stages-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://BMSC@dev.azure.com/BMSC/Infrastructura/_git/ArgoCD
    targetRevision: main
    path: argocd/apps/portal-comercial/stages/children
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ServerSideApply=true
